apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ocm-kustomization
  namespace: flux-system
spec:
  interval: 1m
  path: ./ocm         # 👈 make sure this matches exactly
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 2m
  wait: true