apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: klusterlet
  namespace: open-cluster-management-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: klusterlet
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: clusteradm-charts
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: klusterlet-values
      valuesKey: values.yaml