apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: klusterlet
  namespace: flux-system
spec:
  interval: 1m
  install:
    createNamespace: true
  targetNamespace: open-cluster-management-agent
  chart:
    spec:
      chart: klusterlet
      version: "0.15.2"
      sourceRef:
        kind: HelmRepository
        name: ocm
        namespace: flux-system
  values:
    clusterName: onprem-rancher-np
    deployAgent: true
    registrationImagePullSpec: quay.io/open-cluster-management/registration:latest
    workImagePullSpec: quay.io/open-cluster-management/work:latest