apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: klusterlet
  namespace: open-cluster-management-agent
spec:
  releaseName: klusterlet
  interval: 1m
  chart:
    spec:
      chart: klusterlet
      version: "0.15.2"  # latest as of mid-2025
      sourceRef:
        kind: HelmRepository
        name: ocm
        namespace: flux-system
  install:
    createNamespace: true
    namespace: open-cluster-management-agent
  values:
    clusterName: onprem-rancher-np
    # add extra values if needed