apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: klusterlet
  namespace: flux-system
spec:
  targetNamespace: open-cluster-management-agent   # ✅ Correct placement
  install:
    createNamespace: true                          # ✅ Valid field
  interval: 1m
  chart:
    spec:
      chart: klusterlet
      version: "0.15.2"
      sourceRef:
        kind: HelmRepository
        name: ocm
        namespace: flux-system
  values:
    clusterName: onprem-rancher-np