apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: klusterlet
  namespace: open-cluster-management-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: klusterlet
      sourceRef:
        kind: HelmRepository
        name: ocm
        namespace: flux-system
      version: "*"
  values:
    clusterName: onprem-rancher-np
    hubKubeconfigSecret: bootstrap-hub-kubeconfig
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3