apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: managedcluster-onprem-rancher-np
  namespace: flux-system
spec:
  interval: 1m
  path: ./managedcluster-onprem-rancher-np
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
